### PR TITLE
ACMS-1741: Remove ACMS Site Studio Config Management module

### PR DESCRIPTION
**Pull request by rajeshreeputra**
**Motivation**
Fixes #ACMS-1741

**Proposed changes**
Remove ACMS Site Studio Config Management module.

**Alternatives considered**
NA

**Testing steps**
- Install site with this branch
- install ACMS Site Studio
- import packages
- Execute `drush cex`
- Verify config imported to `config/default/sync` and site studio packages to `config/default/sitestudio`

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Review by chandan-singh7929 — APPROVED** [review]
Since we are deleting acquia_cms_site_studion_cm module from codebase as part of this PR. Changes looks good to me, just wandering what is the use of this feature branch if this module is being deleted?
cc @vishalkhode1

**Comment by vishalkhode1** [comment]
@chandan-singh7929  / @rajeshreeputra Can you confirm if we need this ? If not, then please close this PR and delete branch. Thanks.

**Comment by rajeshreeputra** [comment]
Will review and incorporate required logic in separate PR. 
cc @chandan-singh7929

**Comment by rajeshreeputra** [comment]
Closing as outdated.

**Pull request closed without merging**
