### PR TITLE
ACMS-1501: Update contributed module to latest.

### PR DESCRIPTION
**Pull request by vishalkhode1**
**Motivation**
Update search_api module to 1.27.

**Proposed changes**
Updated composer.json to update search_api module.

**Alternatives considered**
N/A

**Testing steps**
Manual Testing.

**Merge requirements**
- [ ] _Minor change_
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Review by chandan-singh7929 — APPROVED** [review]
Verified changes locally, everything looks good. @vishalkhode1 do you think we should test on cloud environment, since we are updating index there only to see if there any other issue?

**Review by rajeshreeputra — APPROVED** [review]
Changes looks good to me.

**Review by deepakmishra2 — APPROVED** [review]
Looks good to me , verified locally.

**Comment by vishalkhode1** [comment]
> Verified changes locally, everything looks good. @vishalkhode1 do you think we should test on cloud environment, since we are updating index there only to see if there any other issue?

Yes, will do that :)

**Pull request merged**
