### PR TITLE
ACMS-972: Add a param to install command to import from custom config

### PR DESCRIPTION
**Pull request by chandan-singh7929**
**Motivation**

Fixes #[ACMS-972](https://backlog.acquia.com/browse/ACMS-972)

**Proposed changes**

Improve installation time with and without existing configuration.

**Alternatives considered**

NA

**Testing steps**

- Install the site with acquia_cms and observe the installation time taken.

**Merge requirements**
- [_Enhancement_] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Comment by vishalkhode1** [comment]
@chandan-singh7929 I think we now don't need following functions:
1. `acquia_cms_module_implements_alter()`
2. `acquia_cms_modules_installed()`

If not, then we get them removed ?

**Comment by chandan-singh7929** [comment]
> 2\. `acquia_cms_modules_installed()`

@vishalkhode1 - I think above one is required, if module get enable individually and have some site studio components then it should import. Though we can remove implements alter as we have same code in common module.

**Comment by vishalkhode1** [comment]
> > 2. `acquia_cms_modules_installed()`
> 
> @vishalkhode1 - I think above one is required, if module get enable individually and have some site studio components then it should import. Though we can remove implements alter as we have same code in common module.

That anyway will install. Right ?
Because we've unset implementations only when site is getting installed ?
```
if ($hook == 'modules_installed' && InstallerKernel::installationAttempted()) {
  unset($implementations['cohesion_sync']);
}

**Comment by chandan-singh7929** [comment]
@vishalkhode1 - Changes done.

**Comment by vishalkhode1** [comment]
> > > 2. `acquia_cms_modules_installed()`
> > 
> > 
> > @vishalkhode1 - I think above one is required, if module get enable individually and have some site studio components then it should import. Though we can remove implements alter as we have same code in common module.
> 
> That anyway will install. Right ? Because we've unset implementations only when site is getting installed ?
> 
> ```
> if ($hook == 'modules_installed' && InstallerKernel::installationAttempted()) {
>   unset($implementations['cohesion_sync']);
> }
> ```
As discussed, we'll remove `acquia_cms_module_implements_alter()` as we've moved the code to `acquia_cms_common.module` file and we'll keep function `acquia_cms_modules_installed()` for now. If needed, we'll create a separate ticket to verify and then remove.

**Pull request merged**
