### PR TITLE
ACMS-1644: Replace Cohesion patches from Individual GIST URL to drupa…

### PR DESCRIPTION
**Pull request by deepakmishra2**
…l.org URL.

**Motivation**

Fixes #ACMS-1644

**Proposed changes**
Changed patch from gist url to drupal.org url

**Alternatives considered**

**Testing steps**

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Review by apathak18 — APPROVED** [review]
LGTM

**Review by rajeshreeputra — APPROVED** [review]
Changes looks good.

**Comment by chandan-singh7929** [comment]
@deepakmishra2 please update lock file as well so that its get apply for acquia_cms

**Comment by chandan-singh7929** [comment]
@deepakmishra2 - I still don't see lock file here.

**Review by chandan-singh7929 — APPROVED** [review]

**Review by vishalkhode1 — APPROVED** [review]

**Pull request merged**
