### PR TITLE
ACMS-1317: Move to new site studio package management

### PR DESCRIPTION
**Pull request by rajeshreeputra**
**Motivation**
Fixes #ACMS-1317

**Proposed changes**
Update Site Studio package manager to new.

**Alternatives considered**
 PHP Unit test related to site studio i.e. [SiteStudioCoreTest::testSiteStudioCore](https://github.com/acquia/acquia_cms/blob/feature/new-site-studio/modules/acquia_cms_site_studio/tests/src/Functional/SiteStudioCoreTest.php) will fail and taken care in ACMS-1330.

**Testing steps**

- Install site with this code
- Import SS package from UI

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Comment by chandan-singh7929** [comment]
@rajeshreeputra - Overall changes looks good to me, I have few suggestions please take a look.

- Since we are using new site studio package manager to import packages, we no more need below piece of code, since rebuild is already been taken care while importing the package from file `docroot/modules/contrib/acquia_cms_common/src/Commands/Hooks.php`.
`public function importSiteStudioPackagesPostCommand($result, CommandData $commandData) {
    $config = $this->configFactory->get('cohesion.settings');
    if ($config->get('api_key') && $config->get('organization_key')) {
      $this->say(dt('Rebuilding all entities.'));
      $result = $this->acmsUtilityService->rebuildSiteStudio();
      $this->yell('Finished rebuilding.');
      return is_array($result) && isset(array_shift($result)['error']) ? CommandResult::exitCode(self::EXIT_FAILURE) : CommandResult::exitCode(self::EXIT_SUCCESS);
    }
  }`
- When enabling starter module, I can see following errors:
Screenshot 2022-08-02 at 1 30 23 PM
cc: @vishalkhode1

**Review by apathak18 — APPROVED** [review]
PR changes looks good to me.
Validated the changes on my local development.
Noticed no errors and things are working as expected.

**Review by apathak18 — COMMENTED** [review]
@rajeshreeputra could you please check why CI jobs are failing? Otherwise all looks good

**Review by chandan-singh7929 — APPROVED** [review]
LGTM.

**Review by vishalkhode1 — CHANGES_REQUESTED** [review]

**Review by vishalkhode1 — APPROVED** [review]

**Comment by vishalkhode1** [comment]
@rajeshreeputra @chandan-singh7929 @apathak18 I'm merging this PR, assuming all Site Studio configuration files are correct and it's working as expected.

**Pull request merged**
