### PR TITLE
Feature/bounteous headless

### LINKED ISSUE #1070: Headless - Add NextJS Module to ACMS repo
```
As a administrator/ACMS Developer
I want to enable & use acquia_cms_headless module
So that I can use Acquia CMS in headless mode.
```

**Acceptance Criteria:**

1. There should be acquia_cms_headless module under [modules](https://github.com/acquia/acquia_cms/tree/develop/modules) folder of [acquia_cms](https://github.com/acquia/acquia_cms).
2. By default, acquia_cms_headless module shouldn’t be enabled when installing acquia_cms profile.
3. When enabling this module, it should also install & enable [NextJS](https://www.drupal.org/project/next) module.
4. Admin should be able to go into Extend page and enable/uninstall the module. acquia_cms_headless module should be able to install & un-install without any errors.

**Approach:**

1. Add [NextJS](https://github.com/acquia/acquia_cms) module dependency on acquia_cms root [composer.json](https://github.com/acquia/acquia_cms/blob/develop/composer.json) file and it should also be the added in composer.json file of acquia_cms_headless module.
2. If any patches needs to be added, then pin the module version (instead of using min. stability version. Ex: ‘drupal/next:^1.0’ shouldn’t be used instead ‘drupal/next:1.0.0’ should be used).

### PR DESCRIPTION
**Pull request by emb03**
**Motivation**

Fixes #1070 Adds NextJS to ACMS repo

**Proposed changes**

When ACMS Headless Module is enabled the nextJS module(s) will be enabled
On composer install patches will be applied

**Alternatives considered**

None

**Testing steps**

Run composer install
Enable the ACMS Headless module

**Merge requirements**
- [ ]  _Enhancement_
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Comment by modularlab** [comment]
@emb03 Are you able to decline this so that we can re-submit a more clean PR?

**Comment by emb03** [comment]
@msherron This PR is closed, do you still me to to "decline"? I don't see that option.

**Comment by msherron** [comment]
It automatically closed when I merged in the changes from develop. Do you have changes on your branch you haven't pushed to `origin` on `feature/bounteous-headless` ?

**Comment by modularlab** [comment]
@emb03 I posted that before @msherron had made updates.  So we're good.  

@msherron we do have additional changes but we'll create a new PR for those.  Thanks.  I haven't had a chance to look yet but does this branch also now include the new plugins used on the tour dashboard?

**Pull request merged**
