### PR TITLE
ACMS-897: Allow custom profile to install & configure site studio fro…

### PR DESCRIPTION
**Pull request by chandan-singh7929**
…m site install form

**Motivation**

Fixes #[ACMS-897]

**Proposed changes**

Patch acquia/cohesion due to current issue [ACO-1169](https://backlog.acquia.com/browse/ACO-1169) to fix site install using UI

**Alternatives considered**

N/A
**Testing steps**

- composer create-project drupal/recommended-project drupal9
- cd drupal9
- composer config minimum-stability dev
- composer config repositories.acquia_cms_profile_generator vcs 'git@github.com:acquia/acquia_cms_profile_generator.git'
- composer require acquia/acquia_cms_profile_generator
- ./vendor/bin/robo acquia:generate-profile
- Generate the profile and make sure to include acquia_cms_page module (This will automatically include acquia_cms_sit_studio module).
- Install the site using custom profile created above. After all modules are installed from the custom profile, you'll see user is redirected back to install page.
- 
**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Comment by chandan-singh7929** [comment]
Note: Allowing patches to be applied from dependencies
If you want your project to accept patches from dependencies, you must have the following in your composer file:
```
{
  "extra": {
      "enable-patching": true
  }
}
```

**Review by vishalkhode1 — CHANGES_REQUESTED** [review]
@chandan-singh7929 Can you move those patches from root composer.json as well ?

**Comment by chandan-singh7929** [comment]
> @chandan-singh7929 Can you remove those patches from root composer.json as well ?

@vishalkhode1 - If we remove patches from root composer.json it will not apply for acquia_cms because we have not required components module in  root composer.json

**Comment by vishalkhode1** [comment]
> > @chandan-singh7929 Can you remove those patches from root composer.json as well ?
> 
> @vishalkhode1 - If we remove patches from root composer.json it will not apply for acquia_cms because we have not required components module in root composer.json

Correct, makes sense.

**Review by vishalkhode1 — APPROVED** [review]

**Review by vishalkhode1 — APPROVED** [review]

**Pull request merged**
