### PR TITLE
ACMS-723: Upgrade Site Studio to 6.5.0

### PR DESCRIPTION
**Pull request by chandan-singh7929**
**Motivation**
ACMS-723

**Proposed changes**

Refactor cohesionFacade class as per site studio 6.5.0
**Alternatives considered**

**Testing steps**

Run site install and check everything is working as expected
**Merge requirements**
- [_Major change_] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [x] Manual testing by a reviewer

### CODE REVIEW

**Comment by chandan-singh7929** [comment]
During site install I noticed below one error:
```
[notice] Importing package: profiles/contrib/acquia_cms/config/dx8/cohesion_website_settings.default_font_settings.yml_
[error]  argument `$map` of `map-get($map, $key)` must be a map 
[error]  API Error while trying to save Website settings - Default font settings 
```
and when ran `drush cohesion:rebuild` got this:
```
drush cohesion:rebuild
>  Rebuilding all entities.
>  [notice] Importing styles for elements
>  [notice] Rebuilding all styles
>  [notice] Building cohesion_color - Brand color - brand-color
>  [notice] Building cohesion_color - Brand color light - brand-color-light
>  [notice] Building cohesion_color - Gray 80 - gray-80
>  [notice] Rebuilding all styles
>  [notice] Rebuilding all styles
>  [notice] Rebuilding all styles
>  [notice] Rebuilding all styles
>  [error]  argument `$map` of `map-get($map, $key)` must be a map 
>  [error]  API Error while trying to save Website settings - Default font settings 
>  [error]  argument `$map` of `map-get($map, $key)` must be a map 
>  [error]  API Error while trying to save Website settings - Default font settings 
>  [notice] Building cohesion_website_settings - Default font settings - default_font_settings
>  [notice] Rebuilding all styles
>  [notice] Rebuilding all styles
>  [notice] Rebuilding all styles
>  [error]  Message: Unable to generate assets, please try again. If the problem persists, contact 
> your administrator.
>  
>  [error]  Message: Site Studio rebuild failed to complete. argument `$map` of `map-get($map, 
> $key)` must be a map
>  
                                             
              Finished rebuilding.           
```

**Comment by panshulK** [comment]
Hey @chandan-singh7929 , Followed the following steps - 

- Switched to your branch (ACMS-723) on cloud IDE.
- Ran composer install (Completed without any issues)
- Ran dursh site:install (Completed without any issues)
- Upon running `drush cohesion:rebuild` noticed the error mentioned above : 
`>  [error]  Message: Site Studio rebuild failed to complete. argument `$map` of `map-get($map,` 

Due to this, the cohesion rebuild fails in completing the setup.

**Comment by chandan-singh7929** [comment]
I check the latest update here with site install, now its working fine. through messages are showing on screen while we need to wait for 20-30 min to get installation completed.

**Comment by panshulK** [comment]
Hey @chandan-singh7929 

Tested the latest changes on this branch. Re-tested both UI and Drush installation, I'm now able to see -
- Logs showing up correctly using drush command
- Successful installation on both drush & UI installation.

**Comment by panshulK** [comment]
I can verify that with latest changes I'm able to see the installation completing successfully. Verified with the following ways - 
1. Tested installation with & without Site Studio Keys, I'm able to see all the components being imported successfully.
2. Tested Installation with drush commands, I'm able to see all the messages logging successfully and also all the components are being imported successfully.
3. Tested Installation  using UI (screenshots attached below), I'm able to see all the components are being imported successfully.
4. Installation of the starter module via UI+Drush is successful
5. I'm able to use components on Page Content Type landing page.

Screenshots Attached as follows : 
Screenshot 2021-04-06 at 6 41 51 PM

**Review by vishalkhode1 — APPROVED** [review]

**Pull request merged**
