### PR TITLE
Merge feature/refactor-role-permissions branch into develop

### PR DESCRIPTION
**Pull request by deepakmishra2**
**Motivation**

Fixes #[ACMS-1358](https://backlog.acquia.com/browse/ACMS-1358)

**Proposed changes**

**Alternatives considered**

**Testing steps**

**Merge requirements**
- [ ] _Major change_, _Minor change_, _Bug_, _Enhancement_, and/or _Chore_ label applied
- [ ] Manual testing by a reviewer

### CODE REVIEW

**Comment by rajeshreeputra** [comment]
@deepakmishra2 please rebase feature/refactor-role-permissions with develop

**Review by rajeshreeputra — APPROVED** [review]
LGTM

**Comment by chandan-singh7929** [comment]
I can see one test failure locally:
`
1) Drupal\Tests\acquia_cms_audio\Functional\AudioTest::testMediaType
Behat\Mink\Exception\ExpectationException: Current response status code is 403, but 200 expected.`

**Review by chandan-singh7929 — APPROVED** [review]
Overall changes looks good to me, but CI tests are taking more than 2hrs which is not good, also this is getting termination due to time out. we need to find some alternative.

**Review by apathak18 — APPROVED** [review]
Looks good to me.

**Review by vishalkhode1 — APPROVED** [review]

**Pull request merged**
